[package]
name = "oysters_client"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[features]
lru = ["oysters_core/lru"]
persistance = ["oysters_core/persistance", "oysters_core/bundled_sqlite"]
default = ["lru", "persistance"]

[dependencies]
reqwest = { version = "0.12.14", features = ["json"] }
oysters_core = { path = "../oysters_core", features = [
    "serde",
], default-features = false }
